# Generated by Django 3.2 on 2023-05-13 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0003_alter_cat_cat_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_alter_services_service_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('special_instructions', models.TextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cats', models.ManyToManyField(to='cat.Cat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('service_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_level', to='service.services')),
            ],
        ),
    ]
