# Generated by Django 3.2 on 2023-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'Checkout'},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
