# Generated by Django 3.2 on 2023-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_choice', models.IntegerField(choices=[('1', 'Package 1 - 30 minutes'), ('2', 'Package 2 - 60 minutes')], default=1, null=True)),
            ],
        ),
    ]
