# Generated by Django 3.2 on 2023-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Package Price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_choice',
            field=models.CharField(choices=[(1, '30 minutes'), (2, '60 minutes')], max_length=50, null=True, verbose_name='Service Choice'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.TextField(max_length=400, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Service Name'),
        ),
    ]
