# Generated by Django 3.2 on 2023-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20230509_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_choice',
            field=models.CharField(choices=[('1', '30 minutes'), ('2', '60 minutes')], max_length=50, null=True, verbose_name='Service Choice'),
        ),
    ]
